name: Flight Booking CICD

on:
  push:
    branches:
      - develop
      - main

jobs:
  upload-to-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Upload `variables.json` to Composer bucket
      - name: Upload Variables JSON to GCS
        run: |
          gsutil cp variables/dev/variables.json gs://us-central1-airflow-gds-4d94d43e-bucket/data/dev/variables.json

      # Import Variables into Airflow-DEV (Fixed environment name)
      - name: Import Variables into Airflow-DEV
        run: |
          gcloud composer environments run airflow-gds \
            --location us-central1 \
            variables import -- /home/airflow/gcs/data/dev/variables.json

      # Sync Spark job to GCS
      - name: Upload Spark Job to GCS
        run: |
          gsutil cp spark_job/spark_transformation_job.py gs://airflow-projects-gds-03012026/airflow-flight-booking-CICD-Project/spark-job/

      # Sync Airflow DAG to Airflow DEV Composer
      - name: Upload Airflow DAG to DEV
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-gds \
            --location us-central1 \
            --source airflow_job/airflow_job.py

  upload-to-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Upload `variables.json` to Composer bucket
      - name: Upload Variables JSON to GCS
        run: |
          gsutil cp variables/prod/variables.json gs://us-central1-airflow-prod-2ec72436-bucket/data/prod/variables.json

      # Import Variables into Airflow-PROD
      - name: Import Variables into Airflow-PROD
        run: |
          gcloud composer environments run airflow-prod \
            --location us-central1 \
            variables import -- /home/airflow/gcs/data/prod/variables.json

      # Sync Spark job to GCS
      - name: Upload Spark Job to GCS
        run: |
          gsutil cp spark_job/spark_transformation_job.py gs://airflow-projects-gds-03012026/airflow-flight-booking-CICD-Project/spark-job/

      # Sync Airflow DAG to Airflow PROD Composer
      - name: Upload Airflow DAG to PROD
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-prod \
            --location us-central1 \
            --source airflow_job/airflow_job.py